from modules.droneposition import DronePosition
class Constants:
    NUM_DRONES=5
    STANDARD_ALTITUDE=30
    MODULE_SPEED=5
    COHESION_FACTOR=0.01
    ALIGNEMENT_FACTOR=0.1
    SEPARATION_FACTOR=0.8
    SEPARATION_RADIUS=1
    NEIGHBOR_RADIUS=16
    DRONE_PROGRESS=10
    STARTING_RADIUS=8
    MAX_PASSES=8
    EXAMPLE_DESTINATION=DronePosition(47.6,8.6,25)

   